# Generated by Django 6.0.4 on 2026-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
