# Generated by Django 6.0.4 on 2026-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_historicalstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
